package it.unisa.petra.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import it.unisa.petra.core.Process;
import it.unisa.petra.core.ProcessOutput;
import it.unisa.petra.core.exceptions.ADBNotFoundException;
import it.unisa.petra.core.exceptions.AppNameCannotBeExtractedException;
import it.unisa.petra.core.exceptions.NoDeviceFoundException;
import it.unisa.petra.core.exceptions.NumberOfTrialsExceededException;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MainUI extends JDialog {
    private JPanel contentPane;
    private JTextField apkLocationField;
    private JLabel apkLocationLabel;
    private JButton apkLocationButton;
    private JSlider interactionsSlider;
    private JLabel interactionsLabel;
    private JLabel timeBetweenInteractionsLabel;
    private JSlider timeBetweenInteractionsSlider;
    private JTextField scriptLocationField;
    private JButton scriptLocationButton;
    private JLabel scriptLocationLabel;
    private JSlider runsSlider;
    private JLabel runsLabel;
    private JLabel powerProfileFileLabel;
    private JTextField powerProfileFileField;
    private JButton powerProfileFileButton;
    private JTextArea statusArea;
    private JProgressBar progressBar;
    private JButton startEstimationButton;
    private JButton statisticsButton;
    private JScrollPane statusAreaScroll;
    private JLabel scriptTimeField;
    private JSpinner scriptTimeSpinner;
    private JLabel interactionToolField;
    private JRadioButton monkeyRadioButton;
    private JRadioButton monkeyrunnerRadioButton;
    private MouseAdapter scriptLocationMouseAdapter;
    private String appName;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    MainUI() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("PETrA");
        setResizable(false);
        setContentPane(contentPane);
        setModal(true);
        pack();

        scriptLocationMouseAdapter = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                scriptLocationButtonActionPerformed();
            }
        };

        apkLocationButton.addActionListener(evt -> apkLocationButtonActionPerformed());
        apkLocationField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                apkLocationButtonActionPerformed();
            }
        });
        powerProfileFileButton.addActionListener(evt -> powerProfileFileButtonActionPerformed());
        powerProfileFileField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                powerProfileFileButtonActionPerformed();
            }
        });
        monkeyRadioButton.addActionListener(evt -> setMonkeyRadioButtonActionPerformed());
        monkeyrunnerRadioButton.addActionListener(evt -> setMonkeyrunnerRadioButtonActionPerformed());
        scriptLocationButton.addActionListener(evt -> scriptLocationButtonActionPerformed());
        startEstimationButton.addActionListener(evt -> startEstimationButtonActionPerformed());
        statisticsButton.addActionListener(evt -> statisticsButtonActionPerformed());
        statusAreaScroll.setViewportView(statusArea);

        PrintStream out = new PrintStream(new TextAreaOutputStream(statusArea));
        System.setOut(out);

        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width) / 2 - getWidth() / 2, (Toolkit.getDefaultToolkit().getScreenSize().height) / 2 - getHeight() / 2);
    }

    public static void run() {
        try {
            OUTER:
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if (info.getName() != null) {
                    switch (info.getName()) {
                        case "GTK+":
                            UIManager.setLookAndFeel(info.getClassName());
                            break OUTER;
                        case "Windows":
                            UIManager.setLookAndFeel(info.getClassName());
                            break OUTER;
                        case "Nimbus":
                            UIManager.setLookAndFeel(info.getClassName());
                            break;
                        default:
                            break;
                    }
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainUI dialog = new MainUI();
        EventQueue.invokeLater(
                () -> dialog.setVisible(true)
        );
    }

    private void apkLocationButtonActionPerformed() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Apk Files", "apk");
        chooser.setFileFilter(filter);
        int res = chooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            apkLocationField.setText(filename);
        }
    }

    private void powerProfileFileButtonActionPerformed() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML Files", "xml");
        chooser.setFileFilter(filter);
        int res = chooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            powerProfileFileField.setText(filename);
        }
    }

    private void setMonkeyRadioButtonActionPerformed() {
        scriptLocationField.setText("");
        scriptTimeSpinner.setValue(0);
        interactionsSlider.setEnabled(true);
        timeBetweenInteractionsSlider.setEnabled(true);
        scriptLocationField.setEnabled(false);
        scriptLocationField.removeMouseListener(scriptLocationMouseAdapter);
        scriptLocationButton.setEnabled(false);
        scriptTimeSpinner.setEnabled(false);
        startEstimationButton.setEnabled(true);
    }

    private void setMonkeyrunnerRadioButtonActionPerformed() {
        interactionsSlider.setEnabled(false);
        timeBetweenInteractionsSlider.setEnabled(false);
        scriptLocationField.setEnabled(true);
        scriptLocationField.addMouseListener(scriptLocationMouseAdapter);
        scriptLocationButton.setEnabled(true);
        scriptTimeSpinner.setEnabled(true);
        startEstimationButton.setEnabled(true);
    }

    private void scriptLocationButtonActionPerformed() {
        JFileChooser chooser = new JFileChooser();
        int res = chooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            scriptLocationField.setText(filename);
        }
    }

    private void startEstimationButtonActionPerformed() {
        statusArea.setText(null);
        statisticsButton.setEnabled(false);

        String apkLocationPath = apkLocationField.getText();
        int runs = runsSlider.getValue();
        int interactions = interactionsSlider.getValue();
        int timeBetweenInteractions = timeBetweenInteractionsSlider.getValue();
        int scriptTime = (int) scriptTimeSpinner.getValue();
        String scriptLocationPath = scriptLocationField.getText();
        String powerProfilePath = powerProfileFileField.getText();

        boolean valid = true;

        if (apkLocationPath.isEmpty()) {
            System.out.println("Apk location missing.");
            valid = false;
        }

        if (monkeyrunnerRadioButton.isSelected()) {
            if (scriptLocationPath.isEmpty()) {
                System.out.println("You must select a script to be executed.");
                valid = false;
            } else {
                if (scriptTime <= 0) {
                    System.out.println("You must select the estimated time needed for executing the script.");
                    valid = false;
                }
            }
        }

        if (!valid) {
            return;
        }

        progressBar.setValue(0);

        MainUI.Task task = new MainUI.Task(apkLocationPath, interactions, timeBetweenInteractions,
                scriptLocationPath, scriptTime, runs, powerProfilePath);
        task.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            if ("progress".equals(evt1.getPropertyName())) {
                progressBar.setValue((Integer) evt1.getNewValue());
            }
        });
        task.execute();
    }

    private void statisticsButtonActionPerformed() {
        this.dispose();
        appName = "a2dp.Vol";
        String outputLocationPath = new File(apkLocationField.getText()).getParent() + File.separator + "test_data" + File.separator + appName;
        new StatsUI(outputLocationPath);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(9, 5, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder("Monkeyrunner Options"));
        scriptLocationLabel = new JLabel();
        scriptLocationLabel.setText("Script Location");
        panel1.add(scriptLocationLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scriptLocationField = new JTextField();
        scriptLocationField.setEditable(false);
        scriptLocationField.setToolTipText("The location of the Monkeyrunner script.");
        panel1.add(scriptLocationField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(400, -1), null, 0, false));
        scriptLocationButton = new JButton();
        scriptLocationButton.setEnabled(false);
        scriptLocationButton.setIcon(new ImageIcon(getClass().getResource("/folder.png")));
        scriptLocationButton.setText("Open");
        scriptLocationButton.setToolTipText("Select monkeyrunner script.");
        panel1.add(scriptLocationButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scriptTimeField = new JLabel();
        scriptTimeField.setText("Time needed for executing the script");
        panel1.add(scriptTimeField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scriptTimeSpinner = new JSpinner();
        scriptTimeSpinner.setEnabled(false);
        panel1.add(scriptTimeSpinner, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        progressBar = new JProgressBar();
        progressBar.setStringPainted(true);
        contentPane.add(progressBar, new GridConstraints(6, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPane.add(spacer2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 0, false));
        final Spacer spacer3 = new Spacer();
        contentPane.add(spacer3, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 0, false));
        statusAreaScroll = new JScrollPane();
        contentPane.add(statusAreaScroll, new GridConstraints(5, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        statusArea = new JTextArea();
        statusArea.setColumns(0);
        statusArea.setEditable(false);
        statusArea.setEnabled(true);
        statusArea.setRows(8);
        statusAreaScroll.setViewportView(statusArea);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel2, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder("Monkey Options"));
        interactionsSlider = new JSlider();
        interactionsSlider.setEnabled(false);
        interactionsSlider.setMajorTickSpacing(500);
        interactionsSlider.setMaximum(5000);
        interactionsSlider.setMinimum(100);
        interactionsSlider.setMinorTickSpacing(100);
        interactionsSlider.setPaintLabels(true);
        interactionsSlider.setPaintTicks(true);
        interactionsSlider.setSnapToTicks(true);
        interactionsSlider.setToolTipText("Time between an Android Monkey event and the next one in ms.");
        interactionsSlider.setValue(100);
        panel2.add(interactionsSlider, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(400, -1), null, 0, false));
        interactionsLabel = new JLabel();
        interactionsLabel.setText("Interactions");
        panel2.add(interactionsLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        timeBetweenInteractionsLabel = new JLabel();
        timeBetweenInteractionsLabel.setText("Time Between Interactions");
        panel2.add(timeBetweenInteractionsLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        timeBetweenInteractionsSlider = new JSlider();
        timeBetweenInteractionsSlider.setEnabled(false);
        timeBetweenInteractionsSlider.setMajorTickSpacing(500);
        timeBetweenInteractionsSlider.setMaximum(5000);
        timeBetweenInteractionsSlider.setMinimum(100);
        timeBetweenInteractionsSlider.setMinorTickSpacing(100);
        timeBetweenInteractionsSlider.setPaintLabels(true);
        timeBetweenInteractionsSlider.setPaintTicks(true);
        timeBetweenInteractionsSlider.setSnapToTicks(true);
        timeBetweenInteractionsSlider.setToolTipText("Number of Android Monkey event to perform.");
        timeBetweenInteractionsSlider.setValue(100);
        panel2.add(timeBetweenInteractionsSlider, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(400, -1), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 7, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel3, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        powerProfileFileLabel = new JLabel();
        powerProfileFileLabel.setText("Power Profile File");
        panel3.add(powerProfileFileLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        powerProfileFileField = new JTextField();
        powerProfileFileField.setEditable(false);
        powerProfileFileField.setEnabled(true);
        powerProfileFileField.setToolTipText("Device power profile (see https://source.android.com/devices/tech/power/).");
        panel3.add(powerProfileFileField, new GridConstraints(1, 1, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        apkLocationField = new JTextField();
        apkLocationField.setEditable(false);
        apkLocationField.setToolTipText("Apk to analyze.");
        panel3.add(apkLocationField, new GridConstraints(0, 1, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, -1), null, 0, false));
        apkLocationButton = new JButton();
        apkLocationButton.setIcon(new ImageIcon(getClass().getResource("/folder.png")));
        apkLocationButton.setText("Open");
        apkLocationButton.setToolTipText("Select apk.");
        panel3.add(apkLocationButton, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        powerProfileFileButton = new JButton();
        powerProfileFileButton.setIcon(new ImageIcon(getClass().getResource("/folder.png")));
        powerProfileFileButton.setText("Open");
        powerProfileFileButton.setToolTipText("Select power profile file.");
        panel3.add(powerProfileFileButton, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        runsLabel = new JLabel();
        runsLabel.setText("Runs");
        panel3.add(runsLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        runsSlider = new JSlider();
        runsSlider.setMajorTickSpacing(5);
        runsSlider.setMaximum(30);
        runsSlider.setMinimum(1);
        runsSlider.setMinorTickSpacing(1);
        runsSlider.setPaintLabels(true);
        runsSlider.setPaintTicks(true);
        runsSlider.setSnapToTicks(true);
        runsSlider.setValue(1);
        panel3.add(runsSlider, new GridConstraints(2, 1, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        apkLocationLabel = new JLabel();
        apkLocationLabel.setText("Apk Location");
        panel3.add(apkLocationLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        interactionToolField = new JLabel();
        interactionToolField.setText("Tool for perform interactions");
        panel3.add(interactionToolField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        monkeyRadioButton = new JRadioButton();
        monkeyRadioButton.setText("Monkey");
        monkeyRadioButton.setToolTipText("Select a tool.");
        panel3.add(monkeyRadioButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        monkeyrunnerRadioButton = new JRadioButton();
        monkeyrunnerRadioButton.setText("Monkeyrunner");
        monkeyrunnerRadioButton.setToolTipText("Select a tool.");
        panel3.add(monkeyrunnerRadioButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        statisticsButton = new JButton();
        statisticsButton.setEnabled(false);
        statisticsButton.setIcon(new ImageIcon(getClass().getResource("/graph.png")));
        statisticsButton.setText("Statistics");
        statisticsButton.setToolTipText("View statistics.");
        contentPane.add(statisticsButton, new GridConstraints(8, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, 45), null, 0, false));
        startEstimationButton = new JButton();
        startEstimationButton.setEnabled(false);
        startEstimationButton.setIcon(new ImageIcon(getClass().getResource("/play-button.png")));
        startEstimationButton.setText("Start Energy Estimation");
        startEstimationButton.setToolTipText("Start the process.");
        contentPane.add(startEstimationButton, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(250, 45), null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(monkeyRadioButton);
        buttonGroup.add(monkeyrunnerRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    class Task extends SwingWorker<Void, Void> {

        private final String apkLocationPath;
        private final int interactions;
        private final int timeBetweenInteractions;
        private final String scriptLocationPath;
        private final int scriptTime;
        private final int runs;
        private String powerProfilePath;

        Task(String apkLocationPath, int interactions, int timeBetweenInteractions, String scriptLocationPath,
             int scriptTime, int runs, String powerProfilePath) {
            this.apkLocationPath = apkLocationPath;
            this.interactions = interactions;
            this.timeBetweenInteractions = timeBetweenInteractions;
            this.scriptTime = scriptTime;
            this.scriptLocationPath = scriptLocationPath;
            this.runs = runs;
            this.powerProfilePath = powerProfilePath;
        }

        @Override
        public Void doInBackground() {
            try {
                apkLocationButton.setEnabled(false);
                powerProfileFileField.setEditable(false);
                runsSlider.setEnabled(false);
                interactionsSlider.setEnabled(false);
                timeBetweenInteractionsSlider.setEnabled(false);
                scriptLocationField.setEditable(false);
                scriptLocationButton.setEnabled(false);
                powerProfileFileButton.setEnabled(false);
                startEstimationButton.setEnabled(false);
                Process process = new Process();
                setProgress(0);
                int progress;
                int trials = 0;
                BufferedWriter seedsWriter = null;

                appName = process.extractAppName(apkLocationPath);

                String outputLocationPath = new File(apkLocationPath).getParent() + File.separator + "test_data" + File.separator + appName;

                File appDataFolder = new File(outputLocationPath);

                appDataFolder.mkdirs();

                if (this.scriptLocationPath.isEmpty()) {
                    File seedsFile = new File(outputLocationPath + File.separator + "seeds");
                    seedsWriter = new BufferedWriter(new FileWriter(seedsFile, true));
                }
                process.installApp(apkLocationPath);

                if (this.powerProfilePath.isEmpty()) {
                    process.extractPowerProfile(outputLocationPath);
                    this.powerProfilePath = outputLocationPath + "/power_profile.xml";
                }

                int timeCapturing = (interactions * timeBetweenInteractions) / 1000;

                if (!scriptLocationPath.isEmpty()) {
                    timeCapturing = scriptTime;
                }

                for (int run = 1; run <= runs; run++) {
                    if (trials == 10) {
                        throw new NumberOfTrialsExceededException();
                    }
                    try {
                        ProcessOutput output = process.playRun(run, appName, interactions, timeBetweenInteractions, timeCapturing,
                                scriptLocationPath, powerProfilePath, outputLocationPath, appName);
                        if (seedsWriter != null) {
                            seedsWriter.append(String.valueOf(output.getSeed())).append("\n");
                        }
                        timeCapturing = output.getTimeCapturing();
                        progress = (100 * run / runs);
                        setProgress(progress);
                    } catch (InterruptedException | IOException ex) {
                        run--;
                        trials++;
                    }
                }
                apkLocationButton.setEnabled(true);
                powerProfileFileField.setEditable(true);
                runsSlider.setEnabled(true);
                interactionsSlider.setEnabled(true);
                timeBetweenInteractionsSlider.setEnabled(true);
                scriptLocationField.setEditable(true);
                scriptLocationButton.setEnabled(true);
                powerProfileFileButton.setEnabled(true);
                startEstimationButton.setEnabled(true);
                statisticsButton.setEnabled(true);
                process.uninstallApp(appName);
            } catch (NoDeviceFoundException | AppNameCannotBeExtractedException | IOException | NumberOfTrialsExceededException |
                    ADBNotFoundException ex) {
                apkLocationButton.setEnabled(true);
                powerProfileFileField.setEditable(true);
                runsSlider.setEnabled(true);
                interactionsSlider.setEnabled(true);
                timeBetweenInteractionsSlider.setEnabled(true);
                scriptLocationField.setEditable(true);
                scriptLocationButton.setEnabled(true);
                powerProfileFileButton.setEnabled(true);
                startEstimationButton.setEnabled(true);
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            return null;
        }
    }
}
